name       : roccat-tools
version    : 5.6.0
release    : 2
source     :
    - https://kent.dl.sourceforge.net/project/roccat/roccat-tools/roccat-tools-5.6.0.tar.bz2 : 9f5d5dc561a3d68883e1b477bb3a23f6721e2900e0d0696ba66ff53dfd61d728
license    : GPL-2.0
component  : system.utils
summary    : Utilities for Roccat hardware devices
description: |
    Utilities for Roccat hardware devices
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gaminggear-0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(lua-5.3)
    - pkgconfig(x11)
setup      : |
    %cmake -DWITH_LUA="5.3" .
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    mv $installdir/usr/lib/udev $installdir/usr/lib64/udev
    rmdir $installdir/etc $installdir/usr/lib
patterns   :
    - arvo :
        - /usr/bin/*arvo*
        - /usr/lib64/udev/rules.d/*arvo*
        - /usr/lib64/*arvo*
        - /usr/lib64/*/*arvo*
        - /usr/share/applications/*arvo*
        - /usr/share/man/*/*/*arvo*
    - isku :
        - /usr/bin/*isku*
        - /usr/lib64/udev/rules.d/*isku*
        - /usr/lib64/*isku*
        - /usr/lib64/*/*isku*
        - /usr/share/applications/*isku*
        - /usr/share/man/*/*/*isku*
    - iskufx :
        - /usr/bin/*iskufx*
        - /usr/lib64/udev/rules.d/*iskufx*
        - /usr/lib64/*iskufx*
        - /usr/lib64/*/*iskufx*
        - /usr/share/applications/*iskufx*
        - /usr/share/man/*/*/*iskufx*
    - kone :
        - /usr/bin/*kone*
        - /usr/lib64/udev/rules.d/*kone*
        - /usr/lib64/*kone*
        - /usr/lib64/*/*kone*
        - /usr/share/applications/*kone*
        - /usr/share/man/*/*/*kone*
    - konextd :
        - /usr/bin/*konextd*
        - /usr/lib64/udev/rules.d/*konextd*
        - /usr/lib64/*konextd*
        - /usr/lib64/*/*konextd*
        - /usr/share/applications/*konextd*
        - /usr/share/man/*/*/*konextd*
    - konextdoptical :
        - /usr/bin/*konextdoptical*
        - /usr/lib64/udev/rules.d/*konextdoptical*
        - /usr/lib64/*konextdoptical*
        - /usr/lib64/*/*konextdoptical*
        - /usr/share/applications/*konextdoptical*
        - /usr/share/man/*/*/*konextdoptical*
    - koneplus :
        - /usr/bin/*koneplus*
        - /usr/lib64/udev/rules.d/*koneplus*
        - /usr/lib64/*koneplus*
        - /usr/lib64/*/*koneplus*
        - /usr/share/applications/*koneplus*
        - /usr/share/man/*/*/*koneplus*
    - konepure :
        - /usr/bin/*konepure*
        - /usr/lib64/udev/rules.d/*konepure*
        - /usr/lib64/*konepure*
        - /usr/lib64/*/*konepure*
        - /usr/share/applications/*konepure*
        - /usr/share/man/*/*/*konepure*
    - konepuremilitary :
        - /usr/bin/*konepuremilitary*
        - /usr/lib64/udev/rules.d/*konepuremilitary*
        - /usr/lib64/*konepuremilitary*
        - /usr/lib64/*/*konepuremilitary*
        - /usr/share/applications/*konepuremilitary*
        - /usr/share/man/*/*/*konepuremilitary*
    - konepureoptical :
        - /usr/bin/*konepureoptical*
        - /usr/lib64/udev/rules.d/*konepureoptical*
        - /usr/lib64/*konepureoptical*
        - /usr/lib64/*/*konepureoptical*
        - /usr/share/applications/*konepureoptical*
        - /usr/share/man/*/*/*konepureoptical*
    - kova2016 :
        - /usr/bin/*kova2016*
        - /usr/lib64/udev/rules.d/*kova2016*
        - /usr/lib64/*kova2016*
        - /usr/lib64/*/*kova2016*
        - /usr/share/applications/*kova2016*
        - /usr/share/man/*/*/*kova2016*
    - kovaplus :
        - /usr/bin/*kovaplus*
        - /usr/lib64/udev/rules.d/*kovaplus*
        - /usr/lib64/*kovaplus*
        - /usr/lib64/*/*kovaplus*
        - /usr/share/applications/*kovaplus*
        - /usr/share/man/*/*/*kovaplus*
    - kiro :
        - /usr/bin/*kiro*
        - /usr/lib64/udev/rules.d/*kiro*
        - /usr/lib64/*kiro*
        - /usr/lib64/*/*kiro*
        - /usr/share/applications/*kiro*
        - /usr/share/man/*/*/*kiro*
    - nyth :
        - /usr/bin/*nyth*
        - /usr/lib64/udev/rules.d/*nyth*
        - /usr/lib64/*nyth*
        - /usr/lib64/*/*nyth*
        - /usr/share/applications/*nyth*
        - /usr/share/man/*/*/*nyth*
    - pyra :
        - /usr/bin/*pyra*
        - /usr/lib64/udev/rules.d/*pyra*
        - /usr/lib64/*pyra*
        - /usr/lib64/*/*pyra*
        - /usr/share/applications/*pyra*
        - /usr/share/man/*/*/*pyra*
    - ryosmk :
        - /usr/bin/*ryosmk*
        - /usr/lib64/udev/rules.d/*ryosmk*
        - /usr/lib64/*ryosmk*
        - /usr/lib64/*/*ryosmk*
        - /usr/share/applications/*ryosmk*
        - /usr/share/man/*/*/*ryosmk*
    - ryosmkfx :
        - /usr/bin/*ryosmkfx*
        - /usr/lib64/udev/rules.d/*ryosmkfx*
        - /usr/lib64/*ryosmkfx*
        - /usr/lib64/*/*ryosmkfx*
        - /usr/share/applications/*ryosmkfx*
        - /usr/share/man/*/*/*ryosmkfx*
    - ryostkl :
        - /usr/bin/*ryostkl*
        - /usr/lib64/udev/rules.d/*ryostkl*
        - /usr/lib64/*ryostkl*
        - /usr/lib64/*/*ryostkl*
        - /usr/share/applications/*ryostkl*
        - /usr/share/man/*/*/*ryostkl*
    - savu :
        - /usr/bin/*savu*
        - /usr/lib64/udev/rules.d/*savu*
        - /usr/lib64/*savu*
        - /usr/lib64/*/*savu*
        - /usr/share/applications/*savu*
        - /usr/share/man/*/*/*savu*
    - skeltr :
        - /usr/bin/*skeltr*
        - /usr/lib64/udev/rules.d/*skeltr*
        - /usr/lib64/*skeltr*
        - /usr/lib64/*/*skeltr*
        - /usr/share/applications/*skeltr*
        - /usr/share/man/*/*/*skeltr*
    - sova :
        - /usr/bin/*sova*
        - /usr/lib64/udev/rules.d/*sova*
        - /usr/lib64/*sova*
        - /usr/lib64/*/*sova*
        - /usr/share/applications/*sova*
        - /usr/share/man/*/*/*sova*
    - suora :
        - /usr/bin/*suora*
        - /usr/lib64/udev/rules.d/*suora*
        - /usr/lib64/*suora*
        - /usr/lib64/*/*suora*
        - /usr/share/applications/*suora*
        - /usr/share/man/*/*/*suora*
    - tyon :
        - /usr/bin/*tyon*
        - /usr/lib64/udev/rules.d/*tyon*
        - /usr/lib64/*tyon*
        - /usr/lib64/*/*tyon*
        - /usr/share/applications/*tyon*
        - /usr/share/man/*/*/*tyon*
