name       : roccat-tools
version    : 5.9.0
release    : 4
source     :
    - https://sourceforge.net/projects/roccat/files/roccat-tools/roccat-tools-5.9.0.tar.bz2/download : 6f6766309bace2aece09910912d4a6d8bec61c9b4432f4f3ed388ebf7e16408a
homepage   : http://roccat.sourceforge.net/
license    : GPL-2.0-or-later
component  :
    - system.utils
    - arvo : system.utils
    - isku : system.utils
    - iskufx : system.utils
    - kone : system.utils
    - koneplus : system.utils
    - konepure : system.utils
    - konepuremilitary : system.utils
    - konepureoptical : system.utils
    - konextd : system.utils
    - konextdoptical : system.utils
    - kova2016 : system.utils
    - kovaplus : system.utils
    - lua : system.utils
    - nyth : system.utils
    - pyra : system.utils
    - ryosmk : system.utils
    - ryosmkfx : system.utils
    - ryostkl : system.utils
    - savu : system.utils
    - skeltr : system.utils
    - sova : system.utils
    - suora : system.utils
    - tyon : system.utils
summary    :
    - Utilities for Roccat hardware devices
    - arvo : Roccat Arvo userlandtools
    - isku : Roccat Isku userlandtools
    - iskufx : Roccat IskuFX userlandtools
    - kiro : Roccat Kiro userlandtools
    - kone : Roccat Kone userlandtools
    - koneplus : Roccat Kone[+] userlandtools
    - konepure : Roccat KonePure userlandtools
    - konepuremilitary : Roccat KonePureMilitary/Black userlandtools
    - konepureoptical : Roccat KonePureOptical userlandtools
    - konextd : Roccat KoneXTD userlandtools
    - konextdoptical : Roccat KoneXTDOptical userlandtools
    - kova2016 : Roccat Kova 2016 userlandtools
    - kovaplus : Roccat Kova[+] userlandtools
    - lua : Roccat Lua userlandtools
    - nyth : Roccat Nyth userlandtools
    - pyra : Roccat Pyra userlandtools
    - ryosmk : Roccat Ryos MK userlandtools
    - ryosmkfx : Roccat Ryos MK FX userlandtools
    - ryostkl : Roccat Ryos TKL userlandtools
    - savu : Roccat Savu userlandtools
    - skeltr : Roccat Skeltr userlandtools
    - sova : Roccat Sova userlandtools
    - suora : Roccat Suora userlandtools
    - tyon : Roccat Tyon userlandtools
description:
    - Roccat consists of a shared library and other files shared by device specific applications for roccat hardware.
    - arvo : Arvo consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Arvo keyboard.
    - isku : Isku consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Isku keyboard.
    - iskufx : IskuFX consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat IskuFX keyboard.
    - kiro : Kiro consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Kiro mouse.
    - kone : Kone consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Kone mouse.
    - koneplus : Koneplus consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Kone[+] mouse.
    - konepure : Konepure consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat KonePure mouse.
    - konepuremilitary : Konepuremilitary consists of a console application and a GUI application. It helps to manipulate the Profiles and Settings of a Roccat KonePureMilitary/Black mouse.
    - konepureoptical : Konepureoptical consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat KonePureOptical mouse.
    - konextd : Konextd consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat KoneXTD mouse.
    - konextdoptical : Konextdoptical consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat KoneXTDOptical mouse.
    - kova2016 : Kova2016 consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Kova 2016 mouse.
    - kovaplus : Kovaplus consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Kova[+] mouse.
    - lua : Lua consists of a console application and a GUI application. It helps users to manipulate the Settings of a Roccat Lua mouse.
    - nyth : Nyth consists of a console application and a GUI application. It helps users to manipulate the Settings of a Roccat Nyth mouse.
    - pyra : Pyra consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Pyra mouse.
    - ryosmk : Ryosmk consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of Roccat Ryos MK keyboards.
    - ryosmkfx : Ryosmkfx consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of Roccat Ryos MK FX keyboards.
    - ryostkl : Ryostkl consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of Roccat Ryos TKL keyboards.
    - savu : Savu consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Savu mouse.
    - skeltr : Skeltr consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Skeltr keyboard.
    - sova : Sova consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Sova keyboard.
    - suora : Suora consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Suora keyboard.
    - tyon : Tyon consists of a console application and a GUI application. It helps users to manipulate the Profiles and Settings of a Roccat Tyon mouse.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gaminggear-0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(lua-5.3)
    - pkgconfig(x11)
setup      : |
    %apply_patches
    %cmake -DWITH_LUA="5.3" .
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    mv $installdir/usr/lib/udev $installdir/usr/lib64/udev
    rmdir $installdir/etc $installdir/usr/lib
patterns   :
    - arvo :
        - /usr/bin/*arvo*
        - /usr/lib64/udev/rules.d/*arvo*
        - /usr/lib64/*arvo*
        - /usr/lib64/*/*arvo*
        - /usr/share/applications/*arvo*
        - /usr/share/man/*/*/*arvo*
    - isku :
        - /usr/bin/*isku*
        - /usr/lib64/udev/rules.d/*isku*
        - /usr/lib64/*isku*
        - /usr/lib64/*/*isku*
        - /usr/share/applications/*isku*
        - /usr/share/man/*/*/*isku*
    - iskufx :
        - /usr/bin/*iskufx*
        - /usr/lib64/udev/rules.d/*iskufx*
        - /usr/lib64/*iskufx*
        - /usr/lib64/*/*iskufx*
        - /usr/share/applications/*iskufx*
        - /usr/share/man/*/*/*iskufx*
    - kiro :
        - /usr/bin/*kiro*
        - /usr/lib64/udev/rules.d/*kiro*
        - /usr/lib64/*kiro*
        - /usr/lib64/*/*kiro*
        - /usr/share/applications/*kiro*
        - /usr/share/man/*/*/*kiro*
    - kone :
        - /usr/bin/*kone*
        - /usr/lib64/udev/rules.d/*kone*
        - /usr/lib64/*kone*
        - /usr/lib64/*/*kone*
        - /usr/share/applications/*kone*
        - /usr/share/man/*/*/*kone*
    - koneplus :
        - /usr/bin/*koneplus*
        - /usr/lib64/udev/rules.d/*koneplus*
        - /usr/lib64/*koneplus*
        - /usr/lib64/*/*koneplus*
        - /usr/share/applications/*koneplus*
        - /usr/share/man/*/*/*koneplus*
    - konepure :
        - /usr/bin/*konepure*
        - /usr/lib64/udev/rules.d/*konepure*
        - /usr/lib64/*konepure*
        - /usr/lib64/*/*konepure*
        - /usr/share/applications/*konepure*
        - /usr/share/man/*/*/*konepure*
    - konepuremilitary :
        - /usr/bin/*konepuremilitary*
        - /usr/lib64/udev/rules.d/*konepuremilitary*
        - /usr/lib64/*konepuremilitary*
        - /usr/lib64/*/*konepuremilitary*
        - /usr/share/applications/*konepuremilitary*
        - /usr/share/man/*/*/*konepuremilitary*
    - konepureoptical :
        - /usr/bin/*konepureoptical*
        - /usr/lib64/udev/rules.d/*konepureoptical*
        - /usr/lib64/*konepureoptical*
        - /usr/lib64/*/*konepureoptical*
        - /usr/share/applications/*konepureoptical*
        - /usr/share/man/*/*/*konepureoptical*
    - konextd :
        - /usr/bin/*konextd*
        - /usr/lib64/udev/rules.d/*konextd*
        - /usr/lib64/*konextd*
        - /usr/lib64/*/*konextd*
        - /usr/share/applications/*konextd*
        - /usr/share/man/*/*/*konextd*
    - konextdoptical :
        - /usr/bin/*konextdoptical*
        - /usr/lib64/udev/rules.d/*konextdoptical*
        - /usr/lib64/*konextdoptical*
        - /usr/lib64/*/*konextdoptical*
        - /usr/share/applications/*konextdoptical*
        - /usr/share/man/*/*/*konextdoptical*
    - kova2016 :
        - /usr/bin/*kova2016*
        - /usr/lib64/udev/rules.d/*kova2016*
        - /usr/lib64/*kova2016*
        - /usr/lib64/*/*kova2016*
        - /usr/share/applications/*kova2016*
        - /usr/share/man/*/*/*kova2016*
    - kovaplus :
        - /usr/bin/*kovaplus*
        - /usr/lib64/udev/rules.d/*kovaplus*
        - /usr/lib64/*kovaplus*
        - /usr/lib64/*/*kovaplus*
        - /usr/share/applications/*kovaplus*
        - /usr/share/man/*/*/*kovaplus*
    - lua :
        - /usr/bin/*lua*
        - /usr/lib64/udev/rules.d/*lua*
        - /usr/lib64/*lua*
        - /usr/lib64/*/*lua*
        - /usr/share/applications/*lua*
        - /usr/share/man/*/*/*lua*
    - nyth :
        - /usr/bin/*nyth*
        - /usr/lib64/udev/rules.d/*nyth*
        - /usr/lib64/*nyth*
        - /usr/lib64/*/*nyth*
        - /usr/share/applications/*nyth*
        - /usr/share/man/*/*/*nyth*
    - pyra :
        - /usr/bin/*pyra*
        - /usr/lib64/udev/rules.d/*pyra*
        - /usr/lib64/*pyra*
        - /usr/lib64/*/*pyra*
        - /usr/share/applications/*pyra*
        - /usr/share/man/*/*/*pyra*
    - ryosmk :
        - /usr/bin/*ryosmk*
        - /usr/lib64/udev/rules.d/*ryosmk*
        - /usr/lib64/*ryosmk*
        - /usr/lib64/*/*ryosmk*
        - /usr/share/applications/*ryosmk*
        - /usr/share/man/*/*/*ryosmk*
    - ryosmkfx :
        - /usr/bin/*ryosmkfx*
        - /usr/lib64/udev/rules.d/*ryosmkfx*
        - /usr/lib64/*ryosmkfx*
        - /usr/lib64/*/*ryosmkfx*
        - /usr/share/applications/*ryosmkfx*
        - /usr/share/man/*/*/*ryosmkfx*
    - ryostkl :
        - /usr/bin/*ryostkl*
        - /usr/lib64/udev/rules.d/*ryostkl*
        - /usr/lib64/*ryostkl*
        - /usr/lib64/*/*ryostkl*
        - /usr/share/applications/*ryostkl*
        - /usr/share/man/*/*/*ryostkl*
    - savu :
        - /usr/bin/*savu*
        - /usr/lib64/udev/rules.d/*savu*
        - /usr/lib64/*savu*
        - /usr/lib64/*/*savu*
        - /usr/share/applications/*savu*
        - /usr/share/man/*/*/*savu*
    - skeltr :
        - /usr/bin/*skeltr*
        - /usr/lib64/udev/rules.d/*skeltr*
        - /usr/lib64/*skeltr*
        - /usr/lib64/*/*skeltr*
        - /usr/share/applications/*skeltr*
        - /usr/share/man/*/*/*skeltr*
    - sova :
        - /usr/bin/*sova*
        - /usr/lib64/udev/rules.d/*sova*
        - /usr/lib64/*sova*
        - /usr/lib64/*/*sova*
        - /usr/share/applications/*sova*
        - /usr/share/man/*/*/*sova*
    - suora :
        - /usr/bin/*suora*
        - /usr/lib64/udev/rules.d/*suora*
        - /usr/lib64/*suora*
        - /usr/lib64/*/*suora*
        - /usr/share/applications/*suora*
        - /usr/share/man/*/*/*suora*
    - tyon :
        - /usr/bin/*tyon*
        - /usr/lib64/udev/rules.d/*tyon*
        - /usr/lib64/*tyon*
        - /usr/lib64/*/*tyon*
        - /usr/share/applications/*tyon*
        - /usr/share/man/*/*/*tyon*
